config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users 
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search" # 検索ボタンが押された時、Searchesコントローラーのsearchアクションが実行されるように定義

  get 'tagsearches/search', to: 'tagsearches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy] 
    resource :favorites, only: [:create, :destroy]
  end 
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search" => "users#search" 
  end
  
  resources :chats, only: [:show, :create]
  
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail" 
    get "send/mail" => "groups#send_mail"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end # endを追加

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    @comment.save
  end

  def destroy
    @comment = BookComment.find(params[:id])
    @comment.destroy
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
  # def create
  #   book = Book.find(params[:book_id])
  #   comment = current_user.book_comments.new(book_comment_params)
  #   comment.book_id = book.id 
  #   comment.save
  #   #redirect_to book_path(book)
  # end
  
  # def destroy
  #   BookComment.find(params[:id]).destroy
  #   #redirect_to book_path(params[:book_id])
  # end
  
  # private
  
  # def book_comment_params
  #   params.require(:book_comment).permit(:comment)
  # end
  
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_counter.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], local: false) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100 comment-textarea" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

<!--<div class="mt-3">-->
<!--  %= form_with model: [@book, @book_comment], local: false do |f| %>-->
<!--    %= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>-->
<!--    %= f.submit "送信する" %>-->
<!--  % end %>-->
<!--</div>-->

app/views/book_comments/_index.html.erb
<table>
  <tbody>
      <% book.book_comments.each do |book_comment| %>
      <tr>
        
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image, size: "100x100" %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right", remote: true %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

<!--<table>-->
<!--  <tbody>-->
<!--      % book.book_comments.each do |book_comment| %>-->
<!--      <tr>-->
        
<!--        <td>-->
<!--          %= link_to user_path(book_comment.user) do %>-->
<!--            %= image_tag book_comment.user.get_profile_image, size: "100x100" %><br>-->
<!--            %= book_comment.user.name %>-->
<!--          % end %>-->
<!--        </td>-->
<!--        <td>%= book_comment.comment %></td>-->
<!--        <td>-->
<!--          % if book_comment.user == current_user %>-->
<!--            %= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>-->
<!--          % end %>-->
<!--        </td>-->
<!--      </tr>-->
<!--      % end %>-->
<!--  </tbody>-->
<!--</table>-->

app/views/book_comments/_show.html.erb
<div class="d-inline-flex flex-column">
  <p>コメント件数:<span id="comment_count"><%= @book.book_comments.count %></span></p>
    <% @book.book_comments.each do |book_comment| %>
      <%= image_tag book_comment.user.get_profile_image, size: "100x100" %>
      <%= book_comment.user.name %>
      <%= book_comment.created_at.strftime('%Y/%m?%d') %><%= book_comment.comment %>
      <% if book_comment.user == current_user %> 
        <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote:true, data: {"turbolinks" => false} %>
      <% end %>
    <% end %>
</div> 

app/views/book_comments/create.js.erb
$('.comment-textarea').val("")
$('.book-comments-counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>")
$('.book-comments-index').html("<%= j(render 'book_comments/index', book: @comment.book) %>")

<!--$('#book-comments').html("%= j(render "book_comments/show", book: @book) %>");-->
<!--$('#comment_count').html("%= @book.book_comments.count %>")-->

app/views/book_comments/destroy.js.erb
$('.book-comments-counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>")
$('.book-comments-index').html("<%= j(render 'book_comments/index', book: @comment.book) %>")

<!--$('#book-comments').html("%= j(render "book_comments/show", book: @book) %>");-->
<!--$('#comment_count').html("%= @book.book_comments.count %>")-->
<!--$("textarea").val('');-->