config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users 
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search" # 検索ボタンが押された時、Searchesコントローラーのsearchアクションが実行されるように定義

  get 'tagsearches/search', to: 'tagsearches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy] 
    resource :favorites, only: [:create, :destroy]
  end 
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search" => "users#search" 
  end
  
  resources :chats, only: [:show, :create]
  
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail" 
    get "send/mail" => "groups#send_mail"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end # endを追加

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # belongs_to :books
  has_one_attached :profile_image
  has_many :books, dependent: :destroy  
  has_many :book_comments, dependent: :destroy 
  has_many :favorites, dependent: :destroy  # Userモデルにも追加
  
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  
  # # フォローをした、されたの関係
  # # has_many :xxxはアソシエーションが繋がっているテーブル名、class_nameは実際のモデルの名前、foreign_keyは外部キーとして何を持つかを表しています。
  # has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # # 一覧画面で使う
  # #「has_many :テーブル名, through: :中間テーブル名」 の形を使って、テーブル同士が中間テーブルを通じてつながっていることを表現します。(followerテーブルとfollowedテーブルのつながりを表す）
  # # 例えば、has_many :yyyにfollowedを入れてしまうと、followedテーブルから中間テーブルを通ってfollowerテーブルにアクセスすることができなくなってしまいます。
  # #  これを防ぐためにhas_many :yyyには架空のテーブル名を、source: :zzzは実際にデータを取得しにいくテーブル名を書きます。
  # has_many :following_users, through: :followers, source: :followed
  # has_many :follower_users, through: :followeds, source: :follower
  
  # #この結果、@user.yyyとすることでそのユーザーがフォローしている人orフォローされている人の一覧を表示することができるようになります。


  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  
  has_many :view_counts, dependent: :destroy
  
  has_many :group_users, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}  # introductionカラムの追加 

  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  # # フォローしたときの処理
  # def follow(user_id)
  #   followers.create(followed_id: user_id)
  # end
  
  # # フォローを外すときの処理
  # def unfollow(user_id)
  #   followers.find_by(followed_id: user_id).destroy
  # end
  
  # # フォローしていればtrueを返す
  # def following?(user)
  #   following_users.include?(user)
  # end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]  # editアクションを追加 

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    
    # Bookモデルで作成した scopeを利用して、それぞれのデータをわかりやすい名前に代入
    @today_book = @books.created_today  
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    # @following_users = @user.following_users # フォロー数を表示するための記述
    # @follower_users = @user.follower_users # フォロワー数を表示するための記述
  end

  def index
    @users = User.all
    @book = Book.new
  end # endを追加 

  def edit
    @user = User.find(params[:id])  # インスタンス変数を追加
  end

  def update
    if @user.update(user_params)  
      redirect_to user_path(@user), notice: "You have updated user successfully."  # パスのusers_path(@user)の末尾のsを削除 
    else
      render "edit" # render の遷移先をeditに指定 
    end
  end
  
  def search  
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end
  
  # # フォロー一覧
  # def follows
  #   user = User.find(params[:id])
  #   @users = user.following_users
  # end
  
  # # フォロワー一覧
  # def followers
  #   user = User.find(params[:id])
  #   @user = user.follower_users
  # end
 
  private

  def user_params
    params.require(:user).permit(:name, :title, :introduction, :profile_image)  # title を追加 
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id # ログインしているユーザーのidをcurrent_user.idで取得 
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user%>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
        
        <!--<td>%= link_to 'Show', user %></td>-->
        <!--<td>フォロー%= user.followers.count %></td>-->
        <!--<td>フォロワー%= user.followeds.count %></td>-->
        <!--<td>%= render 'relationships/follow_btn', user: current_user %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<!--<table class='table'>-->
<!--  <tr>%= image_tag user.get_profile_image, size:'100x100' %></tr>-->
<!--  <tr>-->
<!--	  <th>name</th>-->
<!--	  <th>%= user.name %></th>-->
<!--  </tr>-->
<!--  <tr>-->
<!--	  <th>introduction</th>-->
<!--	  <th>%= user.introduction %></th>-->
<!--  </tr>-->
<!--  <tr>-->
<!--  <th>Follows</th>-->
<!--    <td>-->
<!--      %= link_to follows_user_path(user) do %>-->
<!--        <h6>%= user.followers.count %></h6>-->
<!--      % end %>-->
<!--    </td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <th>Followers</th>-->
<!--    <td>-->
<!--      %= link_to followers_user_path(user) do %>-->
<!--        <h6>%= user.followeds.count %></h6>-->
<!--      % end %>-->
<!--    </td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <td>-->
<!--      % if current_user != user %>-->
<!--        % if current_user.following?(user) %>-->
<!--          %= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>-->
<!--        % else%>-->
<!--          %= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>-->
<!--        % end %>-->
<!--      % end %>-->
<!--    </td>-->
<!--    <td>-->
<!--      % if current_user != user && current_user.following?(user) && user.following?(current_user) %>-->
<!--        %= link_to 'チャットを始める', chat_path(user.id), class: "ml-3" %>-->
<!--      % end %>-->
<!--    </td>-->
<!--  </tr>-->
<!--</table>-->
　
<div class='row'>
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
  
  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
  <% end %>
</div>

<!--<div class='row'>-->
<!--  %= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>-->
<!--    <i class="fas fa-user-cog"></i>-->
<!--  % end %>-->
<!--</div>-->

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'> 
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Followers</h2> 
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <p>フォロー<%= user.followers.count %></p>
          <% end %>
        </td>
        <td>
          <%= link_to followers_user_path(user) do %>
            <p>フォロワー<%= user.followeds.count %></p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<h2>Follows</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image(50,50) %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td>
            <%= link_to follows_user_path(user) do %>
              <h6>フォロー<%= user.followers.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_user_path(user) do %>
              <h6>フォロワー<%= user.followeds.count %></h6>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'> 
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %> <!-- usersのフォルダから_form.html.erbを探しています。 -->
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | 
      <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>


<!--<h2>User info</h2>-->
<!--%= render 'info', user: current_user %>-->

<!--<h2 class="mt-3">New book</h2>-->
<!--%= render 'books/form', book: @book %> <!-- usersのフォルダから_form.html.erbを探しています。 -->

<!--<h2>Users</h2>-->
<!--%= render 'index',users: @users %>-->

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");  

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %> 
    </div>
    <h2>投稿数の前日比・先週比</h2> 
      <table class="table">
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
        <tr>
          <td><%= @today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <% if @yesterday_book.count == 0 %>
            <td>前日の投稿はなし</td>
          <% else %>
            <td>
              <% @the_day_before =  @today_book.count / @yesterday_book.count  %>
              <%= (@the_day_before * 100).round %>% <!-- 前日比の計算方法は ( 当日の投稿数 / 前日の投稿数 ) * 100 で算出 .round で四捨五入-->
            </td>
          <% end %>
        </tr>
      </table>

      <table class="table">
        <tr>
          <th>今週の投稿数</th>
          <th>前週の投稿数</th>
          <th>前週比</th>
        </tr>
        <tr>
          <td><%= @this_week_book.count %></td>
          <td><%= @last_week_book.count %></td>
          <% if @last_week_book.count == 0 %>
            <td>前週の投稿はなし</td>
          <% else %>
            <td>
              <% @the_week_before =  @this_week_book.count / @last_week_book.count  %>
              <%= (@the_week_before * 100).round %>%
            </td>
          <% end %>
        </tr>
        
        <table class='table table-bordered'> 
          <h4>7日間分の投稿数</h4>
          <thead>
            <tr> 
              <th>６日前</th>
              <th>５日前</th>
              <th>４日前</th>
              <th>３日前</th>
              <th>２日前</th>
              <th>１日前</th>
              <th>今日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_6day_ago.count %></td>
              <td><%= @books.created_5day_ago.count %></td>
              <td><%= @books.created_4day_ago.count %></td>
              <td><%= @books.created_3day_ago.count %></td>
              <td><%= @books.created_2day_ago.count %></td>
              <td><%= @books.created_yesterday.count %></td>
              <td><%= @books.created_today.count %></td>
            </tr>
          </tbody>
      </table>
      <canvas id="myLineChart"></canvas>  
      <script>
        $(document).on('turbolinks:load', function() {
          var ctx = document.getElementById("myLineChart");
          var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
              datasets: [
                {
                  label: '投稿した本の数',
                  data: [
                    <%= @books.created_6day_ago.count %>,
                    <%= @books.created_5day_ago.count %>,
                    <%= @books.created_4day_ago.count %>,
                    <%= @books.created_3day_ago.count %>,
                    <%= @books.created_2day_ago.count %>,
                    <%= @books.created_yesterday.count %>,
                    <%= @books.created_today.count %>
                  ],
                  borderColor: "rgba(0,0,255,1)",
                  backgroundColor: "rgba(0,0,0,0)",
                  tension: 0.4
                }
              ],
            },
            options: {
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
              responsive: true,
              scales: {
                y:{
                  suggestedMin: 0,
                  suggestedMax: 10
                },
                x:{
                  stacked: true
                },
              },
            }
          });
        });
      </script>
       <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %> 
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %> 
      
      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
  </div>
</div>